name: GamelInvPerWorld
author: GamelMC Developement Team
version: 2019.08.20.01 Beta
authors:
  - Karatek_HD
main: de.gamelmc.perworldinventory.main.PerWorldInventory
commands:
  inv:
    description: Opens the inventory of a player.